Ignore packages which dropped Node 6 support
raml-org/datatype-expansion pull request #134
Opened 2020-03-10 10:19 UTC by postatum

2020-04-27 22:09 UTC, jstoiko commented
as discussed, let's drop support for unsupported node versions and support for all currently supported once (v10 onwards)

2020-04-27 22:09 UTC, jstoiko requested changes
as discussed, let's drop support for unsupported node versions and support for all currently supported once (v10 onwards)

2020-04-29 09:19 UTC, postatum commented
> as discussed, let's drop support for unsupported node versions and support for all currently supported once (v10 onwards)

I've reworked the PR to update deps, drop/add Node versions and automate publishing.

2020-04-29 20:59 UTC, jstoiko approved these changes

2020-04-29 20:59 UTC, merged